## Embedded read only data in EnemyData for a single state of intent.
## NOTE: Providing an identical intent_object_id to a higher difficulty level to an
## EnemyData overrides the intent at those difficulty levels and above.
extends SerializableData
class_name EnemyIntentData

const INTENT_INITIAL: String = "intent_initial"

## 意图名称中文映射表，将意图 ID 映射为中文显示名
const INTENT_NAME_ZH: Dictionary[String, String] = {
	"intent_initial": "初始",
	"intent_attack": "攻击",
	"intent_attack_1": "攻击 1",
	"intent_attack_2": "攻击 2",
	"intent_attack_vulnerable": "易伤攻击",
	"intent_attack_multi": "多重攻击",
	"intent_block": "防火墙",
	"intent_summon": "召唤",
	## 第一章 Boss 意图
	"intent_suppress": "压制",
	"intent_pollute": "代码污染",
	"intent_system_reset": "系统重置",
	"intent_repair": "自我修复",
	## 第二章敌人意图
	"intent_scan": "扫描",
	"intent_debuff": "削弱",
	"intent_burn": "灼烧",
	"intent_heavy": "重击",
	"intent_mark": "标记",
	"intent_strike": "连击",
	"intent_fortify": "加固",
	"intent_breach": "突破",
	## 第三章敌人意图
	"intent_overclock": "超频",
	"intent_overheat": "过热",
	"intent_lockdown": "封锁",
	"intent_corrupt": "腐化",
	"intent_crit_buff": "暴击增幅",
	"intent_crit_attack": "暴击",
	"intent_bomb": "植入炸弹",
	"intent_overload": "超载",
	"intent_system_crash": "系统崩溃",
	"intent_emergency": "紧急防护",
	"intent_vent": "泄压",
}

func _init(intent_object_id: String = "", difficulty_level: int = 0, intent_attack_damage: int = 1, intent_number_of_attacks: int = 1, intent_attack_impact_animation_id: String = "", intent_block: int = 0, intent_audio_path: String = "",
intent_next_intent_weights: Dictionary[String, int] = {}, intent_custom_actions: Array[Dictionary] = [], intent_display_types: Array[int] = [], intent_tooltip: String = "") -> void:
	object_id = intent_object_id
	enemy_intent_overrides_id = intent_object_id
	
	# auto format the intent id with the difficulty at the end. This makes it so you don't need to specifiy different names
	# for the same intent which is tedious and easily broken.
	enemy_intent_difficulty_level = difficulty_level
	if difficulty_level > 0:
		object_id = "{0}_d{1}".format([object_id, difficulty_level])
	
	# use object id to derive the intent name, use Chinese mapping if available
	# "intent_<intent_name>" -> "Intent Name"
	enemy_intent_name = INTENT_NAME_ZH.get(intent_object_id, intent_object_id.replace("intent_", "").replace("_", " ").to_pascal_case())
	
	enemy_intent_attack_damage = intent_attack_damage
	enemy_intent_number_of_attacks = intent_number_of_attacks
	enemy_intent_attack_impact_animation_id = intent_attack_impact_animation_id
	enemy_intent_block = intent_block
	enemy_intent_next_intent_weights = intent_next_intent_weights
	enemy_intent_custom_actions = intent_custom_actions
	enemy_intent_audio_path = intent_audio_path
	enemy_intent_display_types = intent_display_types.duplicate(false)
	enemy_intent_tooltip = intent_tooltip
	
	infer_intent_display_types()

## What the intent is called. Mainly for use in the codex. This is automatically
## derived from intent id on initialization for convenience.
@export var enemy_intent_name: String = ""

enum INTENT_DISPLAY_TYPES {
	ATTACKING, # inferred from enemy_intent_attack_damage > 0
	BLOCKING, # inferred from enemy_intent_block > 0
	# determined from custom actions
	DEBUFFING, # enemy is intending to debuff the player
	BUFFING, # enemy is intending to buff themselves
	SUMMONING, # enemy is going to spawn more enemies
	SPECIAL # enemy is doing something unique, like creating cards in player deck
	}

## How the intent will be displayed as in the form of itent icons above the enemy.
## Autogenerated in infer_intent_display_values()
## NOTE: These correspond to hardcoded icons in Enemy above their heads.
@export var enemy_intent_display_types: Array[int] = [
	#INTENT_DISPLAY_TYPES.ATTACKING
	]

## This will be the same as the original id supplied in the constructor.
@export var enemy_intent_overrides_id: String = ""
## The difficulty level when this intent will be introduced.
@export var enemy_intent_difficulty_level: int = 0

## How the intent is displayed in the codex. This is autogenerated via generate_intent_display_text(),
## but additional lines may be supplied
@export var returned_bbcode: String = ""

## Custom tooltip to display when hovering over the intent icon. Used primarily for SPECIAL intents.
@export var enemy_intent_tooltip: String = ""

## If any audio provided, will play as an instant action.
## NOTE: If the enemy is attacking, this will play *per attack*. If no attacks are happening, it
## will play once.
@export var enemy_intent_audio_path: String = ""

## If defined, each attack will create this impact animation vfx
@export var enemy_intent_attack_impact_animation_id: String = ""

## How much damage the enemy will perform with each attack.
@export var enemy_intent_attack_damage: int = 0

## Number of attacks the enemy will perform.
@export var enemy_intent_number_of_attacks: int = 1

## How much block the enemy will gain this intent.
@export var enemy_intent_block: int = 0

## Any additional actions the enemy will perform with this intent.
@export var enemy_intent_custom_actions: Array[Dictionary] = []

## Maps an EnemyIntentData object_id in the EnemyData.enemy_intents to the
## random weighted integer chance of the next intent, defining a random walk.
@export var enemy_intent_next_intent_weights: Dictionary[String, int] = {}

## Figures out the display types (overhead symbols) based on intent's parameters and custom actions.
func infer_intent_display_types() -> void:
	# infer blocking display type
	if enemy_intent_block > 0:
		if not enemy_intent_display_types.has(INTENT_DISPLAY_TYPES.BLOCKING):
			enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.BLOCKING)
	
	# infer attacking display type
	if enemy_intent_attack_damage > 0 or enemy_intent_number_of_attacks > 0:
		if not enemy_intent_display_types.has(INTENT_DISPLAY_TYPES.ATTACKING):
			enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.ATTACKING)

	# infer statuses and summons
	for action: Dictionary in enemy_intent_custom_actions:
		for action_script_path: String in action:
			var action_data: Dictionary = action[action_script_path]
			# summons
			if action_script_path == Scripts.ACTION_SUMMON_ENEMIES:
				enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.SUMMONING)
				
			if action_script_path == Scripts.ACTION_CREATE_CARDS:
				if not enemy_intent_display_types.has(INTENT_DISPLAY_TYPES.SPECIAL):
					enemy_intent_display_types.append(INTENT_DISPLAY_TYPES.SPECIAL)
			
			# statuses
			if action_script_path == Scripts.ACTION_APPLY_STATUS:
				var action_target: int = action_data.get("target_override", BaseAction.TARGET_OVERRIDES.PLAYER)
				var status_effect_object_id: String = action_data.get("status_effect_object_id", "")
				if status_effect_object_id == "":
					DebugLogger.log_warning("EnemyIntentData: No status_effect_object_id supplied for custom status action")
					breakpoint
					continue
				# determine if buffing self or debuffing player
				var status_effect_data: StatusEffectData = Global.get_status_effect_data(status_effect_object_id)
				# buffing enemies
				if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.BUFF:
					if action_target == BaseAction.TARGET_OVERRIDES.PARENT or action_target == BaseAction.TARGET_OVERRIDES.ALL_ENEMIES:
						if not enemy_intent_display_types.has(EnemyIntentData.INTENT_DISPLAY_TYPES.BUFFING):
							enemy_intent_display_types.append(EnemyIntentData.INTENT_DISPLAY_TYPES.BUFFING)
				# debuffing player
				if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.DEBUFF:
					if action_target == BaseAction.TARGET_OVERRIDES.PLAYER:
						if not enemy_intent_display_types.has(EnemyIntentData.INTENT_DISPLAY_TYPES.DEBUFFING):
							enemy_intent_display_types.append(EnemyIntentData.INTENT_DISPLAY_TYPES.DEBUFFING)

## Gets the bbcode needed to display this intent for codex entries.
## NOTE: Extend the bottom section to include more custom action scripts if desired
func get_intent_codex_bbcode(display_type_filter: int = -1) -> String:
	const BBCODE_EMBEDDED_IMAGE_WIDTH: int = 24 # used for statuses and other icons
	var returned_bbcode: String = ""
	
	# blocking
	if enemy_intent_block > 0 and (display_type_filter == -1 or display_type_filter == INTENT_DISPLAY_TYPES.BLOCKING):
		# add to text
		returned_bbcode += "获得 {0} 点防火墙".format([enemy_intent_block])
	
	# attacking
	if (enemy_intent_attack_damage > 0 or enemy_intent_number_of_attacks > 0) and (display_type_filter == -1 or display_type_filter == INTENT_DISPLAY_TYPES.ATTACKING):
		# add to text
		if returned_bbcode.length() > 0:
			returned_bbcode += "\n" # newline
		returned_bbcode += "造成 {0} x {1} 点伤害".format([enemy_intent_attack_damage, enemy_intent_number_of_attacks])
	
	# parse each custom action and use it to generate text from their parameters.
	for action: Dictionary in enemy_intent_custom_actions:
		for action_script_path: String in action:
			var action_data: Dictionary = action[action_script_path]
			match action_script_path:
				# summoning
				Scripts.ACTION_SUMMON_ENEMIES:
					if display_type_filter != -1 and display_type_filter != INTENT_DISPLAY_TYPES.SUMMONING:
						continue
					var random_enemy_object_ids: Array[String] = []
					random_enemy_object_ids.assign(action_data.get("random_enemy_object_ids", []))
					# no enemies being summoned
					if len(random_enemy_object_ids) == 0:
						DebugLogger.log_warning("EnemyIntentData: No random_enemy_object_ids supplied for custom summon action")
						breakpoint
						continue
					
					# newline if needed
					if returned_bbcode.length() > 0:
						returned_bbcode += "\n"
					
					# generate summoning bbcode then format with join
					returned_bbcode += "召唤: "
					var summoning_texts: Array[String] = []
					
					for enemy_id: String in random_enemy_object_ids:
						# add names and icons for each enemy
						var enemy_data: EnemyData = Global.get_enemy_data(enemy_id)
						var summoning_text: String = "{0} [img width={1}]{2}[/img]".format([enemy_data.enemy_name, BBCODE_EMBEDDED_IMAGE_WIDTH, enemy_data.enemy_texture_path])
						summoning_texts.append(summoning_text)
					
					returned_bbcode += ", ".join(summoning_texts)
					
				# statuses
				Scripts.ACTION_APPLY_STATUS:
					# get status parameters
					var action_target: int = action_data.get("target_override", BaseAction.TARGET_OVERRIDES.PLAYER)
					var status_effect_object_id: String = action_data.get("status_effect_object_id", "")
					var status_charge_amount: int = action_data.get("status_charge_amount", 1)
					# invalid status
					if status_effect_object_id == "":
						DebugLogger.log_error("EnemyIntentData: No status_effect_object_id supplied for custom status action")
						breakpoint
						continue
					
					var status_effect_data: StatusEffectData = Global.get_status_effect_data(status_effect_object_id)
					if status_effect_data == null:
						DebugLogger.log_error("EnemyIntentData: Invalid status effect ID {0} supplied for custom status action".format([status_effect_object_id]))
						breakpoint
						continue
					

					# determine if buffing self or debuffing player
					# buffing enemies
					if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.BUFF:
						if action_target == BaseAction.TARGET_OVERRIDES.PARENT or action_target == BaseAction.TARGET_OVERRIDES.ALL_ENEMIES:
							if display_type_filter == -1 or display_type_filter == INTENT_DISPLAY_TYPES.BUFFING:
								if returned_bbcode.length() > 0:
									returned_bbcode += "\n" # newline
								returned_bbcode += "获得 {0} 层 [status_icon:{1}]".format([status_charge_amount, status_effect_object_id])
					# debuffing player or self
					if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.DEBUFF:
						if action_target == BaseAction.TARGET_OVERRIDES.PLAYER:
							if display_type_filter == -1 or display_type_filter == INTENT_DISPLAY_TYPES.DEBUFFING:
								if returned_bbcode.length() > 0:
									returned_bbcode += "\n" # newline
								returned_bbcode += "施加 {0} 层 [status_icon:{1}]".format([status_charge_amount, status_effect_object_id])
						elif action_target == BaseAction.TARGET_OVERRIDES.PARENT or action_target == BaseAction.TARGET_OVERRIDES.ALL_ENEMIES:
							if display_type_filter == -1 or display_type_filter == INTENT_DISPLAY_TYPES.DEBUFFING:
								if returned_bbcode.length() > 0:
									returned_bbcode += "\n" # newline
								returned_bbcode += "陷入 {0} 层 [status_icon:{1}]".format([status_charge_amount, status_effect_object_id])
	
	if enemy_intent_tooltip != "":
		# only show tooltip if not filtering, or if filtering by an intent display type this intent actually has
		if display_type_filter == -1 or enemy_intent_display_types.has(display_type_filter):
			if returned_bbcode.length() > 0:
				returned_bbcode += "\n"
			returned_bbcode += enemy_intent_tooltip
		
	return returned_bbcode
