# tooltip displaying info on a single keyword
# generated by KeywordContainer
extends PanelContainer

const FONT_SIZE: int = 14
const EMBEDDED_IMAGE_SIZE: int = 24

@onready var keyword_rich_text_label: RichLabelAutoSizer = $KeywordRichTextLabel

func init(keyword_object_id: String) -> void:
	var keyword_data: KeywordData = Global.get_keyword_data(keyword_object_id)
	if keyword_data == null:
		DebugLogger.log_error("KeywordTooltip.init(): No keyword of id \"{0}\" found".format([keyword_object_id]))
	else:
		var keyword_bbcode: String = ""
		
		# keyword name
		var prefix_text: String = ""
		if keyword_data.keyword_prefix != "":
			prefix_text = keyword_data.keyword_prefix
		keyword_bbcode = "[color=orange]" + prefix_text + keyword_data.keyword_name + "[/color]"
		
		# prepend status image if it exists
		var keyword_status_effect_id: String = keyword_data.keyword_status_effect_id
		if keyword_status_effect_id != "":
			var status_effect_data: StatusEffectData = Global.get_status_effect_data(keyword_status_effect_id)
			if status_effect_data == null:
				breakpoint
				DebugLogger.log_error("KeywordTooltip.init(): Invald keyword_status_effect_id of \"{0}\"".format([keyword_status_effect_id]))
			else:
				keyword_bbcode = "[img width={0}]{1}[/img] {2}".format([EMBEDDED_IMAGE_SIZE, status_effect_data.status_effect_texture_path, keyword_bbcode])
		
		# append keyword text
		keyword_bbcode = "{0}\n{1}".format([keyword_bbcode, keyword_data.keyword_text_bb_code])
		keyword_bbcode = TextParser.parse(keyword_bbcode, {}, FONT_SIZE)
		
		# force the font to a certain size
		keyword_bbcode = "[font_size={0}]{1}[/font_size]".format([FONT_SIZE, keyword_bbcode])
		keyword_rich_text_label.set_bbcode(keyword_bbcode)
	
		# this must be called deferred to force the rich text to not get clipped
		keyword_rich_text_label.set_deferred("fit_content", true)

func init_custom(title: String, text: String, values: Dictionary = {}) -> void:
	var keyword_bbcode: String = "[color=orange]" + title + "[/color]"
	keyword_bbcode = "{0}\n{1}".format([keyword_bbcode, text])
	keyword_bbcode = TextParser.parse(keyword_bbcode, values, FONT_SIZE)
	keyword_bbcode = "[font_size={0}]{1}[/font_size]".format([FONT_SIZE, keyword_bbcode])
	keyword_rich_text_label.set_bbcode(keyword_bbcode)
	keyword_rich_text_label.set_deferred("fit_content", true)

func init_status_effect(status_effect_object_id: String) -> void:
	var status_effect_data: StatusEffectData = Global.get_status_effect_data(status_effect_object_id)
	if status_effect_data == null:
		DebugLogger.log_error("KeywordTooltip.init_status_effect(): No status effect of id \"{0}\" found".format([status_effect_object_id]))
	else:
		var keyword_bbcode: String = "[color=orange]" + status_effect_data.status_effect_name + "[/color]"
		if status_effect_data.status_effect_texture_path != "":
			keyword_bbcode = "[img width={0}]{1}[/img] {2}".format([EMBEDDED_IMAGE_SIZE, status_effect_data.status_effect_texture_path, keyword_bbcode])
		
		keyword_bbcode = "{0}\n{1}".format([keyword_bbcode, status_effect_data.status_effect_description])
		keyword_bbcode = TextParser.parse(keyword_bbcode, {}, FONT_SIZE)
		keyword_bbcode = "[font_size={0}]{1}[/font_size]".format([FONT_SIZE, keyword_bbcode])
		keyword_rich_text_label.set_bbcode(keyword_bbcode)
		keyword_rich_text_label.set_deferred("fit_content", true)

func init_card(card_object_id: String) -> void:
	var card_data: CardData = Global.get_card_data(card_object_id)
	if card_data == null:
		DebugLogger.log_error("KeywordTooltip.init_card(): No card of id \"{0}\" found".format([card_object_id]))
	else:
		var color_hex = "#ffffff"
		var color_data = Global._id_to_color_data.get(card_data.card_color_id, null)
		if color_data:
			color_hex = "#" + color_data.color.to_html(false)
		
		var display_name: String = card_data.card_name
		if card_data.card_is_playable:
			var cost_str: String = ""
			if card_data.card_energy_cost_is_variable:
				cost_str = "X"
				if card_data.card_energy_cost_variable_upper_bound >= 1:
					cost_str += "-" + str(card_data.card_energy_cost_variable_upper_bound)
			else:
				cost_str = str(card_data.card_energy_cost)
			display_name += "(%s)" % cost_str
			
		var keyword_bbcode: String = "[color=%s]%s[/color]" % [color_hex, display_name]
		
		var parsed_desc = TextParser.parse(card_data.card_description, card_data.card_values, FONT_SIZE)
		keyword_bbcode = "{0}\n{1}".format([keyword_bbcode, parsed_desc])
		keyword_bbcode = "[font_size={0}]{1}[/font_size]".format([FONT_SIZE, keyword_bbcode])
		
		keyword_rich_text_label.set_bbcode(keyword_bbcode)
		keyword_rich_text_label.set_deferred("fit_content", true)
