## Abstract class for any action that needs to perform an action against a set of cards.
## Extend and override perform_action() to provide functionality to the cards.
## NOTE: These actions are designed specifically to work as a child action of ActionBasePickCards, unless you're
## using pick_played_card = true in which case it stands alone.
extends BaseAction
class_name BaseCardsetAction

### Override

func perform_action() -> void:
	# picked_cards = get_picked_cards()
	# iterate over and perform actions against picked_cards
	breakpoint

### Keep

## Gets the cards to use for the cardset action. This can come from a variety of sources.
## Typically generated by an ActionPickCards and can reference the picked_cards from that.
## May also be directly generated and passed in a picked_cards parameter,
## or use the card that invoked it with pick_played_card parameter 
func _get_picked_cards(action_interceptor_processor: ActionInterceptorProcessor = null) -> Array[CardData]:
	# if pick_played_card, use the card that invoked the action as the cardset
	var pick_played_card: bool = (
		action_interceptor_processor.get_shadowed_action_values("pick_played_card", false)
		if action_interceptor_processor != null
		else get_action_value("pick_played_card", false)
	)
	if pick_played_card:
		if card_play_request == null:
			DebugLogger.log_error("BaseCardsetAction._get_picked_cards(): No CardPlayRequest found")
			return []
		elif card_play_request.card_data == null:
			DebugLogger.log_error("BaseCardsetAction._get_picked_cards(): No card found in CardPlayRequest")
			return []
		else:
			# picks currently played card
			var picked_cards: Array[CardData] = []
			picked_cards.append(card_play_request.card_data)
			return picked_cards
	
	# use picked_cards value of this action.
	# NOTE: This may/should aliased with a custom key in some instances
	# and uses values stored in CardPlayRequest
	var picked_cards_value: Variant = (
		action_interceptor_processor.get_shadowed_action_values("picked_cards", null)
		if action_interceptor_processor != null
		else get_action_value("picked_cards", null)
	)
	if picked_cards_value != null:
		var picked_cards: Array = picked_cards_value
		# convert typed array
		var returned_cards: Array[CardData] = []
		for card_data in picked_cards:
			returned_cards.append(card_data)
		return returned_cards
	
	# fall back to the parent action if possible
	if parent_action != null:
		if parent_action is ActionBasePickCards:
			return parent_action.picked_cards
	
	return []

## Cardset actions represent one logical operation. Most have no combatant target, while the few
## target-aware cardset actions can explicitly supply their adjusted targets.
func _intercept_cardset_action(
	interceptor_targets: Array[BaseCombatant] = [null] as Array[BaseCombatant]
) -> Array[ActionInterceptorProcessor]:
	return _intercept_action(interceptor_targets)

func _to_string():
	return "BaseCardset Action"
